services:
  - type: web
    name: vs-hrms-attendance
    env: node
    plan: free
    buildCommand: npm install && cd client && npm install --include=dev && npm run build && cd ../server && npm install
    startCommand: node server/src/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: MONGODB_URI
        sync: false
      - key: TZ
        value: Asia/Kolkata
      - key: SUPERADMIN_EMAIL
        value: admin@hrms.local
      - key: SUPERADMIN_PASSWORD
        value: Admin@123
      - key: SUPERADMIN_NAME
        value: Super Admin
